config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  root "users#login"
  resource :users, only: [:create, :update, :destroy, :edit] do
    post :login, on: :collection
    delete :logout, on: :collection
    resources :tasks
  end
end

app/models/task.rb
class Task < ApplicationRecord
  include ::Elasticsearch::Model
  include ::Elasticsearch::Model::Callbacks

  enum :status, {pending: 0, progress: 1, completed: 2}

  validates :title, presence:true
  validates :status, inclusion: {in: statuses.keys, status: :enum_argument_error}

  belongs_to :user

  before_validation :normalize_title, :normalize_descryption

  after_create :schedule_status_check, :schedule_progress_check, :schedule_progress_status
  after_update :schedule_progress_check, :schedule_progress_status
  
  broadcasts_to ->(task) { "tasks" }

  settings index: {
    max_ngram_diff: 20,
    analysis: {

      analyzer: {
        ngram_analyzer: {
          tokenizer: "ngram_tokenizer",
          filter: ["lowercase"]
        }
      },
      tokenizer: {
        ngram_tokenizer: {
          type: "ngram",
          min_gram: 1,
          max_gram: 10,
          token_chars: ["letter", "digit"]
        }
      }
    }
  } do
    mappings dynamic: 'false' do
      indexes :title, type: 'text', analyzer: 'ngram_analyzer'
      indexes :user_id, type: 'integer'
    end
  end


  def as_indexed_json(options = {})
    self.as_json(
      only: [:title, :descryption, :status, :user_id]
      )
  end

  private

  def normalize_title
    self.title = title.strip if title.present?
  end

  def normalize_descryption
    if (descryption)
      self.descryption = descryption.strip #if descryption.present?
    end
  end

  def schedule_status_check
    TaskStatusCheckJob.set(wait: 30.seconds).perform_later(self.id)
  end

  def schedule_progress_check
    TaskProgressCheckJob.set(wait: 45.seconds).perform_later(self.id)
  end

  def schedule_progress_status
    TaskProgressUpdateJob.set(wait: 1.minute).perform_later(self.id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authorize_request
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      search_results = Task.search({ query: { bool: { must: [ { multi_match: { query: params[:query], fields: ["title"], operator: "and" } } ], filter: [ { term: { user_id: @current_user.id } } ] } } })
      @tasks = search_results.records.order(created_at: :desc)
    else
      @tasks = @current_user.tasks.order(created_at: :desc)
    end

    @tasks = @tasks.page(params[:page]).per(5)

    respond_to do |format|
      format.html
      format.json do
        if @tasks.present?
          render json: {tasks: @tasks.map {|t| TaskSerializer.new(t)}}, status: :ok
        else
          render json: {message: "No tasks"}, status: :ok
        end
      end
    end
  end

  def show
    respond_to do |format|
      format.html { @task }
      format.json { render json: {task: TaskSerializer.new(@task), message: "Task get successfully."}, status: :ok }
    end
  end

  def create
    @task = @current_user.tasks.create!(task_params)
    @tasks = @current_user.tasks.order(created_at: :desc).page(params[:page]).per(5)
    
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to users_tasks_path, notice: "Task created." }
      format.json { render json: {task: TaskSerializer.new(@task), message: "Task created." }, status: :created }
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def update
    if @task.update!(task_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to users_tasks_path, notice: "Task updated." }
        format.json { render json: {task: TaskSerializer.new(@task), message: "Task updated successfully."}, status: :ok }
      end
    end
  end

  def destroy
    if @task.destroy
      respond_to do |format|
        format.html { redirect_back(fallback_location: users_tasks_path, notice: "Task was successfully deleted.") }
        format.json { render json: {message: "Task deleted."}, status: :ok }
      end
    end
  end

  private

  def set_task
    @task = @current_user.tasks.find_by(id: params[:id])
    render json: {message: "Could not find tasks."}, status: :not_found unless @task
  end

  def task_params
    params.require(:task).permit(:title, :descryption, :status)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_edit_form.html.erb
<div class="form-card">

  <h3>Edit Task</h3>

  <%= form_with model: [:users, @task], method: :patch, html: { id: "editTaskForm" } do |f| %>

  <label>Title</label>
  <%= f.text_field :title, placeholder: "Enter title", id: "editTitleField", autofocus:true %>
  
  <% if flash[:error] %>
  <div>
    <p style="color:#e53e3e;font-size: 12px;"><%= flash[:error] %></p>
  </div>
  <% end %>

  <label>Descryption</label>
  <%= f.text_area :descryption, placeholder: "Enter descryption" %>

  <label>Status</label>
  <%= f.select :status, Task.statuses.keys, selected: @task.status %>

  <%= f.submit "Update Task", class: "btn btn-primary" %>

  <% end %>

</div>

app/views/tasks/_form.html.erb
<div  id="task_outer_form">
  <div class="form-card" style="margin: auto; position: relative;">
  

    <%= form_with model: [:users, task || Task.new], data: { turbo_stream: true,
    controller: "task-form",
      action: "submit->task-form#validate" }, html: { id: "taskForm" } do |f| %>
    <div style="display: flex; flex-direction: column;">
    <label>Title</label>
    <%= f.text_field :title, placeholder: "Enter title", autofocus: true, data: { task_form_target: "title" } %>
    <div style="display: block; position: absolute; top: 24%; left: 10%;">
    <p class="field-error"
   data-task-form-target="error"></p>
   </div>
   </div>

    <label>Descryption</label>
    <%= f.text_area :descryption, placeholder: "Enter descryption",class: "descryption" %>

    <label>Status</label>
    <%= f.select :status, Task.statuses.keys %>

    <% if task.persisted? %>
      <%= f.submit "Update Task", class: "btn btn-primary" %>
    <% else %>
      <%= f.submit "Create Task", class: "btn btn-success" %>
    <% end %>

    <% end %>

  </div>  
</div>

app/views/tasks/_pagination.html.erb
<div class="pagination-wrapper" id="pagination_frame">
  <%= paginate @tasks, window: 1  %>
</div>

app/views/tasks/_table.html.erb
<tbody id="tasks" style="width: 100%;">
  <% if @tasks.present? %>
  <%= turbo_stream_from "job_status_channel" %>
  <%= turbo_frame_tag "tasks_list_frame" do %>
    <%= render @tasks %>
  <% end %>
  <% else %>
  <tr>
    <td colspan="3" style="text-align: center; padding: 20px;">
      No tasks available
    </td>
  </tr>
  <% end %>
</tbody>

app/views/tasks/_table.html_v1.erb
<tbody id="tasks" style="width: 100%;">
  <% if @tasks.present? %>
    <%= render @tasks %>
  <% else %>
    <tr>
      <td colspan="3" style="text-align: center; padding: 20px;">
        No tasks available
      </td>
    </tr>
  <% end %>
</tbody>

app/views/tasks/_task.html.erb
<tr id="<%= dom_id task %>">
  <td class="title-cell">
    <div class="task-title"><%= task.title %></div>
  </td>

  <td>
    <span class="badge <%= task.status %>">
      <%= task.status.capitalize %>
    </span>
  </td>

  <td class="actions-cell" style="text-align: center;">
    <%# <%= link_to "Show", users_task_path(task), class: "table-action" %>
    <%= link_to "Edit", edit_users_task_path(task), data: { turbo_stream: true, turbo_method: :get }, class: "table-action edit" %>
    <%= button_to "Delete",
        users_task_path(task),
        method: :delete,
        data: { controller: "confirm", action: "click->confirm#confirm" },
        class: "table-action delete",
        form_class: "inline-form" %>
  </td>
</tr>

app/views/tasks/_task.html_v1.erb
<tr id="<%= dom_id task %>">
  <td class="title-cell">
    <div class="task-title"><%= task.title %></div>
  </td>

  <td>
    <span class="badge <%= task.status %>">
      <%= task.status.capitalize %>
    </span>
  </td>

  <td class="actions-cell" style="text-align: center;">
    <%# <%= link_to "Show", users_task_path(task), class: "table-action" %>
    <%= link_to "Edit", edit_users_task_path(task), data: { turbo_stream: true, turbo_method: :get }, class: "table-action edit" %>
    <%= button_to "Delete",
        users_task_path(task),
        method: :delete,
        data: { controller: "confirm", action: "click->confirm#confirm" },
        class: "table-action delete",
        form_class: "inline-form" %>
  </td>
</tr>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.replace "task_outer_form", partial: "tasks/form", locals: { task: Task.new } %>

<%= turbo_stream.replace "tasks_table_frame" do %>
  <%= turbo_frame_tag "tasks_table_frame" do %>
    <table class="modern-table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Status</th>
          <th class="actions-col" style="text-align: center;">Actions</th>
        </tr>
      </thead>

      <%= render "tasks/table" %>
    </table>
  <% end %>
<% end %>


<%= turbo_stream.replace "pagination_frame", partial: "tasks/pagination", locals: {tasks: Task.order(created_at: :desc).page(1)} %>
<%# <%= turbo_stream.prepend "tasks", @task %>

app/views/tasks/edit.html.erb
<%= render "shared/navbar" %>

<div class="center-wrapper" style="margin-top: 20px;">
  <div class="form-card">

    <%= form_with model: [:users, @task], method: :patch, html: { id: "editTaskForm" } do |f| %>

      <label>Title</label>
      <%= f.text_field :title, placeholder: "Enter title", id: "editTitleField", autofocus:true %>
      
      <% if flash[:error] %>
        <div>
          <p style="color:#e53e3e;font-size: 12px;"><%= flash[:error] %></p>
        </div>
      <% end %>

      <label>Descryption</label>
      <%= f.text_area :descryption, placeholder: "Enter descryption" %>

      <label>Status</label>
      <%= f.select :status, Task.statuses.keys, selected: @task.status %>

      <%= f.submit "Update Task", class: "btn btn-primary" %>

    <% end %>

  </div>
</div>

app/views/tasks/edit.html_v1.erb
<%= render "shared/navbar" %>

<div class="center-wrapper" style="margin-top: 20px;">
  <div class="form-card">

    <%= form_with model: [:users, @task], method: :patch, html: { id: "editTaskForm" } do |f| %>

      <label>Title</label>
      <%= f.text_field :title, placeholder: "Enter title", id: "editTitleField", autofocus:true %>
      
      <% if flash[:error] %>
        <div>
          <p style="color:#e53e3e;font-size: 12px;"><%= flash[:error] %></p>
        </div>
      <% end %>

      <label>Descryption</label>
      <%= f.text_area :descryption, placeholder: "Enter descryption" %>

      <label>Status</label>
      <%= f.select :status, Task.statuses.keys, selected: @task.status %>

      <%= f.submit "Update Task", class: "btn btn-primary" %>

    <% end %>

  </div>
</div>

app/views/tasks/edit.turbo_stream.erb
<%= turbo_stream.replace "task_outer_form",
    partial: "tasks/form",
    locals: { task: @task } %>

app/views/tasks/index.html.erb
<%= render "shared/navbar" %>

<div class="tasks-wrapper" data-controller="reload-redirect" data-redirect-path="<%= users_tasks_path %>" >

  <div>
    <%= turbo_frame_tag "form" do %>
      <%= render "tasks/form", task: Task.new %>
    <% end %>
  </div>

  <div class="header-elastic">
    <div style="width: 25%; margin-top: 5px;">
      <%= form_with url: users_tasks_path, method: :get, class: "elastic", data: { controller: "search", turbo_frame: "tasks_frame" } do |f| %>

        <%= f.text_field :query, placeholder: "Search tasks...", data: { action: "input->search#submit" } %>
      <% end %>
    </div>
    <div class="tasks-header">
      <h2>Your Tasks</h2>
    </div>
  </div>

  <%# <%= turbo_stream_from "job_status_channel" %>

  <%= turbo_frame_tag "tasks_frame" do %>

    <div class="tasks-container">
      <div class="table-card">
      <%= turbo_frame_tag "tasks_table_frame" do %>
        <table class="modern-table">
          <thead>
            <tr>
              <th>Title</th>
              <th>Status</th>
              <th class="actions-col" style="text-align: center;">Actions</th>
            </tr>
          </thead>
          <%= render "tasks/table" %>

        </table>
      <% end %>
      </div>

      <%= render "tasks/pagination" %>
    </div>

  <% end %>

</div>

app/views/tasks/show.html.erb
<%= render "shared/navbar" %>

<div class="center-wrapper">
  <div class="task-card">

    <h3>Task Details</h3>

    <p><b>Title:</b> <%= @task.title %></p>
    <p><b>Description:</b> <%= @task.descryption %></p>
    <p><b>Status:</b> <%= @task.status %></p>

    <%= link_to "Back", users_tasks_path, class: "btn btn-primary" %>

  </div>
</div>

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.replace @task %>

<%= turbo_stream.replace "task_outer_form",
    partial: "tasks/form",
    locals: { task: Task.new } %>