config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  root "users#login"
  resource :users, only: [:create, :update, :destroy, :edit] do
    post :login, on: :collection
    delete :logout, on: :collection
    resources :tasks
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email,
  presence: true,
  uniqueness: true,
  format: {
    with: URI::MailTo::EMAIL_REGEXP,
    message: "must be a valid email address"
  }
  
  validates :password,
  presence: true,
  format: {
    with: /\A(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[^A-Za-z0-9])\S{6,8}\z/,
    message: "must include 1 uppercase, 1 lowercase, 1 special character, 1 number, has length between 6 to 8 characters and does not contain any spaces."
  }
  
  has_many :tasks, dependent: :destroy

  before_validation :normalize_email, :normalize_password
  after_create :send_welcome_email

  private

  def normalize_email
    self.email = email.strip.downcase if email.present?
  end

  def normalize_password
    self.password = password.strip if password.present?
  end

  def send_welcome_email
    SendEmailsJob.set(wait: 1.minute).perform_later(self)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_request, except: [ :create, :login ]

  def create
    user = User.create!(user_params)
    token = set_token(user)
    respond_to do |format|
      format.html { redirect_to users_tasks_path, notice: "User registered successfully." }
      format.json { render json: { user: UserSerializer.new(user), meta: { token: token, message: "User registered successfully." } }, status: :ok }
    end
  end

  def edit
  end

  def update
    if @current_user.update!(password: params[:user][:password])
      respond_to do |format|
        format.html { redirect_to users_tasks_path, notice: "Password updated." }
        format.json { render json: { message: "User updated successfully." }, status: :ok }
      end
    end
  end

  def destroy
    if @current_user.destroy
      session.delete(:token)
      respond_to do |format|
        format.html { redirect_to root_path, notice: "User deleted Successfully." }
        format.json { render json: { message: "User deleted Successfully." }, status: :ok }
      end
    end
  end

  def login
    return if request.get?
    user = User.find_by(email: params[:user][:email].strip.downcase)

    if user && user.authenticate(params[:user][:password])
      token = set_token(user)
      respond_to do |format|
        format.html { redirect_to users_tasks_path, notice: "Logged in successfully." }
        format.json { render json: { user: UserSerializer.new(user), meta: { token: token, message: "Logged in successfully." } }, status: :ok }
      end
    else
      flash[:error] = "Invalid email or password."
      respond_to do |format|
        format.html { redirect_to root_path(form: "login") }
        format.json { render json: { message: "Invalid email or password." }, status: :unauthorized }
      end
    end
  end

  def logout
    session.delete(:token)
    respond_to do |format|
      format.html { redirect_to root_path(form: "login"), notice: "Logged out successfully." }
      format.json { render json: { message: "Logged out successfully." }, status: :ok }
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def set_token(user)
    token = JsonWebToken.encode(user_id: user.id)
    token = "Bearer #{token}"
    response.headers["Authorization"] = token
    session[:token] = token
    token
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_login_form.html.erb
<div class="auth-card" style="">

  <h3>Login</h3>

  <%= form_with scope: :user,
  url: login_users_path,
  data: {
    controller: "auth",
    action: "submit->auth#validate"
  }, novalidate: true do |f| %>

  <label>Email</label>
  <%= f.text_field :email,
  placeholder: "dev@gmail.com",
  data: { auth_target: "email" }, autofocus:true %>
  <small class="error-message" data-auth-target="emailError"></small>


  <label>Password</label>
  <%= f.password_field :password,
  placeholder: "Dev@12",
  data: { auth_target: "password" } %>
  <small class="error-message" data-auth-target="passwordError"></small>

  <% if flash[:error] %>
  <div>
    <p style="color:#e53e3e;font-size: 12px;"><%= flash[:error] %></p>
  </div>
  <% end %>

  <%= f.submit "Login", class: "btn btn-primary" %>

  <% end %>

  <p>
    New user?
    <%= link_to "Register", root_path %>
  </p>

</div>

app/views/users/_register_form.html.erb
<div class="auth-card">

  <h3>Sign Up</h3>

  <%= form_with scope: :user, url: users_path, data: {
    controller: "auth",
    action: "submit->auth#validate"
  }, novalidate: true do |f| %>

    <label>Email</label>
    <%= f.text_field :email, data: { auth_target: "email" }, placeholder: "dev@gmail.com", autofocus: :true %>
    <small class="error-message" data-auth-target="emailError"></small>

    <label>Password</label>
    <%= f.password_field :password, data: { auth_target: "password" }, placeholder: "Dev@12" %>
    <small class="error-message" data-auth-target="passwordError"></small>

    <p class="password-note">
      Must include 1 uppercase, 1 lowercase, 1 special character,
      1 number, 6-8 characters and no spaces.
    </p>

    <% if flash[:error] && flash[:error].match("Email has already been taken") %>
    <div>
      <p style="color:#e53e3e;font-size: 12px;"><%= flash[:error].match("Email has already been taken") %></p>
    </div>
    <% end %>

    <%= f.submit "Register", class: "btn btn-success" %>
  <% end %>

  <p>
    Already registered?
    <%= link_to "Login", root_path(form: "login") %>
  </p>
</div>

app/views/users/edit.html.erb
<%= render "shared/navbar" %>

<div class="center-wrapper">
  <div class="form-card" style="margin-top: 100px;">
    <div style="display: flex; justify-content: space-between; align-items:center; margin-bottom: 10px;">
    <h3>Update Password</h3>
    <%= link_to "Back", users_tasks_path %>
    </div>

    <%= form_with scope: :user,
    url: users_path,
    method: :patch,
    data: {
    controller: "password",
    action: "submit->password#validate"},
    novalidate: true do |f| %>

    <label>New Password</label>
    <%= f.password_field :password,
    placeholder: "Dev@12",
    data: { password_target: "password" }, autofocus:true %>

    <small class="error-message" data-password-target="error"></small>

    <p class="password-note">
      Must include 1 uppercase, 1 lowercase, 1 special character,
      1 number, 6-8 characters and no spaces.
    </p>

    <%= f.submit "Update", class: "btn btn-success" %>

    <% end %>
  </div>
</div>

app/views/users/login.html.erb
<div class="center-wrapper" style="margin-top: 150px;">

  <div>
    <div class="main-heading">Task Manager</div>

    <% if params[:form] == "login" %>
      <%= render "login_form" %>
    <% else %>
      <%= render "register_form" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign In</h1>
<%# create  %>
<%= form_with model: @user do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email, placeholder: "Enter your email" %>
  </div>

  <div>
    <%= form.label :password, "Password" %>
    <%= form.password_field :password, placeholder: "Enter your password" %>
  </div>

  <div>
    <%= form.submit "submit" %>
  </div>

  <%= link_to "Login", login_users_path %>
<% end %>

app/views/users/show.html.erb
<h1>User Details</h1>
<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |

<%= link_to 'Delete User', user_path(@user), data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this user?' } %>